#!/usr/bin/env bash
set -euo pipefail

BASE_MAJOR_VERSION=1
BASE_MINOR_VERSION=5
BASE_PATCH_VERSION=0
VERSION_BASE_COMMIT="c7352b23140d004b59a544fc8e1d4c13dd9127c4"
INCLUDE_NEXT_COMMIT=0

if [[ "${1:-}" == "--next" ]]; then
  INCLUDE_NEXT_COMMIT=1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if git cat-file -e "$VERSION_BASE_COMMIT^{commit}" 2>/dev/null; then
  VERSION_OFFSET="$(git rev-list --count "${VERSION_BASE_COMMIT}..HEAD")"
else
  VERSION_OFFSET="$(git rev-list --count HEAD)"
fi

VERSION_OFFSET=$((VERSION_OFFSET + INCLUDE_NEXT_COMMIT))
PATCH_TOTAL=$((BASE_PATCH_VERSION + VERSION_OFFSET))
MINOR_TOTAL=$((BASE_MINOR_VERSION + PATCH_TOTAL / 10))
MAJOR_TOTAL=$((BASE_MAJOR_VERSION + MINOR_TOTAL / 10))
MINOR_VERSION=$((MINOR_TOTAL % 10))
PATCH_VERSION=$((PATCH_TOTAL % 10))
MARKETING_VERSION="${MAJOR_TOTAL}.${MINOR_VERSION}.${PATCH_VERSION}"
BUILD_VERSION="$VERSION_OFFSET"

cat <<EOF
MARKETING_VERSION=${MARKETING_VERSION}
BUILD_VERSION=${BUILD_VERSION}
VERSION_OFFSET=${VERSION_OFFSET}
EOF
