#!/usr/bin/env bash
set -euo pipefail

BASE_MAJOR_VERSION=1
BASE_MINOR_VERSION=5
BASE_PATCH_VERSION=0

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

LATEST_TAG="$(git tag --list 'build-*' --sort=-version:refname | head -n 1)"

if [[ -n "$LATEST_TAG" ]]; then
  RAW_VERSION="${LATEST_TAG#build-}"
else
  RAW_VERSION="${BASE_MAJOR_VERSION}.${BASE_MINOR_VERSION}.${BASE_PATCH_VERSION}"
fi

IFS='.' read -r CURRENT_MAJOR CURRENT_MINOR CURRENT_PATCH <<< "$RAW_VERSION"

if [[ -z "${CURRENT_PATCH:-}" ]]; then
  CURRENT_PATCH=0
fi

NEXT_PATCH=$((CURRENT_PATCH + 1))
NEXT_MINOR=$CURRENT_MINOR
NEXT_MAJOR=$CURRENT_MAJOR

if (( NEXT_PATCH >= 10 )); then
  NEXT_PATCH=0
  NEXT_MINOR=$((NEXT_MINOR + 1))
fi

if (( NEXT_MINOR >= 10 )); then
  NEXT_MINOR=0
  NEXT_MAJOR=$((NEXT_MAJOR + 1))
fi

MARKETING_VERSION="${NEXT_MAJOR}.${NEXT_MINOR}.${NEXT_PATCH}"

BUILD_VERSION="$(git rev-list --count HEAD)"

cat <<EOF
MARKETING_VERSION=${MARKETING_VERSION}
BUILD_VERSION=${BUILD_VERSION}
PREVIOUS_TAG=${LATEST_TAG}
EOF
